services:
  db:
    image: postgres:16
    container_name: lms_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lms-frand
    ports:
      - "5433:5432"
    volumes:
      - lms_pgdata:/var/lib/postgresql/data

volumes:
  lms_pgdata:
